-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME,B.CATEGORY,SUM(S.total * B.PRICE)
FROM BOOK as B
LEFT OUTER JOIN (SELECT *,SUM(SALES) as total FROM BOOK_SALES WHERE MONTH(SALES_DATE) = 1 GROUP BY BOOK_ID)as S
ON S.BOOK_ID = B.BOOK_ID
LEFT OUTER JOIN (SELECT * FROM AUTHOR) as A
ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY  A.AUTHOR_NAME,B.CATEGORY
ORDER BY  B.AUTHOR_ID,B.CATEGORY desc