-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, sum(PRODUCT.PRICE*OFFLINE_SALE.SALES_AMOUNT) as ll
FROM OFFLINE_SALE
LEFT OUTER JOIN PRODUCT
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
order by ll desc ,  PRODUCT.PRODUCT_CODE

