-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID ,ANIMAL_OUTS.NAME FROM ANIMAL_OUTS INNER JOIN ANIMAL_INS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY DATEDIFF(ANIMAL_INS.DATETIME,ANIMAL_OUTS.DATETIME) limit 2