SELECT C.CAR_ID,C.CAR_TYPE,
ROUND(C.DAILY_FEE * ((100-P.DISCOUNT_RATE) / 100)* 30) as fee
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID 
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE 
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
      AND C.CAR_ID NOT IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                         WHERE END_DATE >= '2022-11-1' 
                               AND START_DATE <= '2022-11-30')
      AND P.DURATION_TYPE = '30일 이상'
GROUP BY C.CAR_ID
HAVING fee >= 500000 and fee<=2000000
ORDER BY fee desc,C.CAR_TYPE  asc, C.CAR_ID desc
      