-- 코드를 입력하세요
SELECT
USED_GOODS_USER.USER_ID,
USED_GOODS_USER.NICKNAME,
CONCAT(USED_GOODS_USER.CITY , " " , USED_GOODS_USER.STREET_ADDRESS1, " ",USED_GOODS_USER.STREET_ADDRESS2),
CONCAT(SUBSTRING(USED_GOODS_USER.TLNO, 1, 3), '-', SUBSTRING(USED_GOODS_USER.TLNO, 4, 4), '-', SUBSTRING(USED_GOODS_USER.TLNO, 8))
FROM USED_GOODS_USER
INNER JOIN (SELECT WRITER_ID, COUNT(*) AS m FROM USED_GOODS_BOARD GROUP BY WRITER_ID)
    AS POST_COUNTS
    ON USED_GOODS_USER.USER_ID = POST_COUNTS.WRITER_ID
where POST_COUNTS.m>=3
ORDER BY USED_GOODS_USER.USER_ID desc