-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE,O.NAME FROM ANIMAL_OUTS as O
LEFT OUTER JOIN (SELECT * FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE "%Intact%") as I
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE  (O.SEX_UPON_OUTCOME  LIKE "%Spayed%" or O.SEX_UPON_OUTCOME  LIKE "%Neutered%" ) and I.NAME is not null