SELECT DATE_FORMAT(o.SALES_DATE,'%Y') AS YEAR, DATE_FORMAT(o.SALES_DATE,'%m') AS MONTH,
u.GENDER, COUNT(DISTINCT(u.USER_ID)) AS USERS
FROM ONLINE_SALE o
LEFT OUTER JOIN USER_INFO u ON u.USER_ID = o.USER_ID  
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER 
ORDER BY YEAR, MONTH, u.GENDER;
