-- 코드를 입력하세요
SELECT 
DISTINCT(CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID), 
 CASE 
            WHEN AVAILABILITY = '대여중' THEN '대여중'
            ELSE '대여 가능'
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
LEFT OUTER JOIN
(SELECT CAR_ID,  
 CASE 
            WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
            ELSE '대여 가능'
        END AS AVAILABILITY

 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE date('2022-10-16')
 between START_DATE and END_DATE) as R
ON R.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID

ORDER BY CAR_ID desc