-- 코드를 입력하세요
SELECT P.PRODUCT_ID , P.PRODUCT_NAME, P.PRICE*total as ll
FROM FOOD_PRODUCT as P
LEFT OUTER JOIN (SELECT *, SUM(AMOUNT) as total FROM FOOD_ORDER  WHERE MONTH(PRODUCE_DATE) = 5 GROUP BY PRODUCT_ID) as O
ON P.PRODUCT_ID = O.PRODUCT_ID
HAVING ll is not null
Order by ll desc, P.PRODUCT_ID