-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
LEFT OUTER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) as total FROM JULY GROUP By FLAVOR ) as JULY
ON FIRST_HALF.FLAVOR = JULY.FLAVOR
ORDER BY (FIRST_HALF.TOTAL_ORDER + JULY.total) DESC limit 3