-- 코드를 입력하세요
SELECT  M.MEMBER_NAME , ll.REVIEW_TEXT, DATE_FORMAT(ll.REVIEW_DATE,'%Y-%m-%d')
FROM REST_REVIEW as ll
LEFT OUTER JOIN MEMBER_PROFILE as M
ON ll.MEMBER_ID = M.MEMBER_ID
WHERE ll.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID
                        ORDER BY COUNT(*) DESC
                        LIMIT 1)
ORDER BY REVIEW_DATE,REVIEW_TEXT