SELECT t.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
JOIN ITEM_TREE t ON i.ITEM_ID = t.ITEM_ID
JOIN ITEM_INFO parent_i ON t.PARENT_ITEM_ID = parent_i.ITEM_ID
WHERE parent_i.RARITY = 'RARE'
ORDER BY t.ITEM_ID DESC;