SELECT MONTH(START_DATE) as ll,CAR_ID,COUNT(*)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (date(START_DATE) between '2022-08-01' and '2022-10-31' ) and
        CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE date(START_DATE) between '2022-08-01' and '2022-10-31' GROUP BY CAR_ID HAVING count(*)>=5)
GROUP BY CAR_ID,ll
ORDER BY ll,CAR_ID desc