SELECT YEAR(d.DIFFERENTIATION_DATE) AS year,
       d2.max_colony - d.SIZE_OF_COLONY AS YEAR_DEV,
       d.ID
FROM ECOLI_DATA d
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS year, 
           MAX(SIZE_OF_COLONY) AS max_colony
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS d2
ON YEAR(d.DIFFERENTIATION_DATE) = d2.year
ORDER BY year ASC , YEAR_DEV ASC; 
