SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO AS i
JOIN FISH_NAME_INFO AS n ON i.FISH_TYPE = n.FISH_TYPE
WHERE i.LENGTH = (
    SELECT MAX(i2.LENGTH)
    FROM FISH_INFO AS i2
    WHERE i2.FISH_TYPE = i.FISH_TYPE
)
order by i.ID