-- 코드를 입력하세요
SELECT
BOARD_ID,
WRITER_ID,
TITLE,
PRICE,
REPLACE(REPLACE(REPLACE(STATUS, "DONE", "거래완료"), "RESERVED", "예약중"),"SALE","판매중")
FROM USED_GOODS_BOARD
WHERE date(CREATED_DATE) between '2022-10-05' and '2022-10-05'
ORDER BY BOARD_ID desc