-- 코드를 입력하세요
SELECT BOOK.CATEGORY , sum(ll.SALES) as TOTAL_SALES
FROM (SELECT * FROM BOOK_SALES WHERE MONTH(SALES_DATE) = 1) as ll
LEFT OUTER JOIN BOOK
ON BOOK.BOOK_ID = ll.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY asc